### ISSUE TITLE
Cipher suites order

### ISSUE THREAD

**Issue by LordMike** [Nauplius/SchannelConfiguration#1]
Hi,

Great initiative!
When comparing with the [IIS crypto tool](https://www.nartac.com/Products/IISCrypto/), would it be possible to add `Cipher Suites Ordering` to the list?

Regards,
Mike

**Comment by LordMike** [comment]
While working out how IIS Crypto does it, I came across this: https://msdn.microsoft.com/en-us/library/bb870930(v=vs.85).aspx

It explains that another setting already allows one to modify the order. So it's up to the developer to decide if it should go in or not.

**Comment by tseward** [comment]
This is available out of the box under Computer Configuration -> Policies -> Administrative Templates -> Network -> SSL Configuration Settings.

**Comment by LordMike** [comment]
Makes sense. I also later on installed your ADMX and realized you'd placed your folder right next to their "SSL Configuration". So, nevermind :).
